# **Numpy**

## **Methods to create numpy arrays**

In [1]:
#creating numpy arrays

import numpy as np  #np is an alias name

## First Method

In [2]:
# Array method (provide a list and it will be created into an array)

arr1= np.array([1,2,3,4,5,5])
arr1

array([1, 2, 3, 4, 5, 5])

In [3]:
# check the type of arr1

type(arr1)

numpy.ndarray

##### Creating 2D array 

In [4]:
#provide list inside a list

arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
type(arr2)

numpy.ndarray

## Second Method

In [6]:
# zeroes Method (Creates a zero matrix)
# pass the shape in form of a tuple

arr3 = np.zeros((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

## Third Method

In [7]:
# ones Method (Creates a ones matrix)
# pass the shape in form of tuple

arr4 = np.ones((3,4))
arr4

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

**By default the data type of each element is float**

## Fourth Method

**Identity matrix is a matrix whose diagonal has 1 as the value**

In [8]:
# Identity Method (Creates an identity matrix)
# pass only one value as its a square matrix

arr5 = np.identity((5))
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Fifth Method

**It is same as the range function in python**

In [9]:
# arange Method (creates a 1D array with given range)

arr6 = np.arange(5,17,2)
arr6

array([ 5,  7,  9, 11, 13, 15])

## Sixth Method

**It creates values with equal difference between them**

In [10]:
# Linspace Method 
# pass the range and the number of values you want between the range

arr7 = np.linspace(10,20,4)
arr7

array([10.        , 13.33333333, 16.66666667, 20.        ])

## Seventh Method

In [11]:
# copy Method 
# It copies any array

arr8 = arr7.copy()
arr8

array([10.        , 13.33333333, 16.66666667, 20.        ])

# **Properties and Attributes**

### 1. Shape (Att)

**Use to check shape of the array**

In [12]:
arr1

array([1, 2, 3, 4, 5, 5])

In [13]:
arr1.shape

(6,)

In [14]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
arr2.shape

(2, 3)

In [16]:
#Creating a 3D array

arr9 = np.array([[[1,2],[4,5]],[[5,6],[7,8]]])
arr9

array([[[1, 2],
        [4, 5]],

       [[5, 6],
        [7, 8]]])

In [17]:
arr9.shape

(2, 2, 2)

### 2. ndim (Att)

**Use to check dimensions of the array**

In [18]:
arr1.ndim

1

In [19]:
arr2.ndim

2

In [20]:
arr9.ndim

3

### 3. Size (Att)

**Use to check number of the items**

In [21]:
arr1

array([1, 2, 3, 4, 5, 5])

In [22]:
arr1.size

6

In [23]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
arr2.size

6

In [25]:
arr9.itemsize

4

**Itemsize tells the memory occupied by the type of values in the array**

### 4. Dtype (Att)

**Tells the dimention type of the array elements**

In [26]:
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [27]:
arr3.dtype

dtype('float64')

In [28]:
arr9

array([[[1, 2],
        [4, 5]],

       [[5, 6],
        [7, 8]]])

In [29]:
arr9.dtype

dtype('int32')

### 5. Astype() (Property)

**This is used to convert any datatype into another**

In [30]:
arr9

array([[[1, 2],
        [4, 5]],

       [[5, 6],
        [7, 8]]])

In [31]:
arr9.dtype

dtype('int32')

In [32]:
# converting arr9 datatype into float

arr9 = arr9.astype('float')

In [33]:
arr9.dtype

dtype('float64')

# **Lists vs Arrays**

## 1. Lesser space than Lists

In [34]:
import sys

**It has a function getsizeof that returns the size of entered value**

In [35]:
# create a list of 100 items and array of 100 items

list1 = range(100)
arr11 = np.arange(100)
arr11 = arr11.astype('int')

In [36]:
# get size of 1 item between 1-100 and multiply with number of values

print(sys.getsizeof(87)*len(list1))  

2800


In [37]:
# get size of one elemnt in array and multiply with total number of items

print(arr11.itemsize * arr11.size)

400


**As array takes 800bytes while list take 2800 bytes**

## 2. Faster than list

In [38]:
# import module that calculates the time of processing

import time

#### For list

In [39]:
# Create two list x and y

x = range(10000000)
y = range(10000000,20000000)

start_time_list = time.time()  # stores the current time

# use zip function to pick elements of both list and add one by one and form new list

z = [(x,y) for x,y in zip(x,y)]

print(time.time() - start_time_list)  # subtract time taken from current time

11.768996953964233


#### For Array

In [40]:
# create two arrays a and b

a = np.arange(10000000)
b = np.arange(10000000,20000000)

start_time_array = time.time()  # current time

c = a + b  # Same as zip function

print(time.time() - start_time_array)

0.3086888790130615


**From above result you can see that their is a time difference**

### Indexing 

In [41]:
arr12 = np.arange(10)
arr12

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
arr12[5]

5

In [43]:
arr12[-1] #negative indexing

9

### Slicing

In [44]:
arr13 = np.arange(24)
arr13

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

**Using reshape function to reshape the array if possible**

In [45]:
arr13 = arr13.reshape(6,4)
arr13

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [46]:
arr13[:3] #prints the first three rows

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [47]:
# to print the third coloum

arr13[:,2]

array([ 2,  6, 10, 14, 18, 22])

In [48]:
# to extract 9 , 10 , 13 , 14

arr13[2:4,1:3]

array([[ 9, 10],
       [13, 14]])

In [49]:
# to extract 18 , 19 , 22 , 23

arr13[4:,2:4]

array([[18, 19],
       [22, 23]])

### Iteration

In [50]:
arr13

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [51]:
# this function gives us each element line by line

for i in np.nditer(arr13):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


# Operations

In [52]:
import numpy as np

### Addition

In [53]:

# create two arrays of same length and add

array1 = np.arange(6)
array2 = np.arange(6,12)

array1 + array2

array([ 6,  8, 10, 12, 14, 16])

### Substaction

In [54]:
# create two arrays of same length and subtract

array3 = np.arange(6)
array4 = np.arange(6,12)

array3 - array4

array([-6, -6, -6, -6, -6, -6])

### Multiplication

In [55]:
# create two arrays of same length and multiply

array5 = np.arange(6)
array6 = np.arange(6,12)

array5 * array6

array([ 0,  7, 16, 27, 40, 55])

### Dot product (Matrix multiplication)

In [56]:
# create two arrays and reshape accordingly

array8 = np.arange(6).reshape(3,2)
array9 = np.arange(6,12).reshape(2,3)

array8.dot(array9)

array([[ 9, 10, 11],
       [39, 44, 49],
       [69, 78, 87]])

In [57]:
array1

array([0, 1, 2, 3, 4, 5])

### greater than or less than

In [58]:
# This returns an array of boolean values 
# True if condition satisfies and false if not

array1>3

array([False, False, False, False,  True,  True])

### Max and Min

In [59]:
array10 = np.arange(2,10).reshape(4,2)
array10

array([[2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [60]:
# To find the max and min of above

array10.min()

2

In [61]:
array10.max()

9

**We can also find max min axis wise**

In [62]:
# The axis 0 gives output coloumn wise while axis 1 gives output row wise

array10.min(axis=0)

array([2, 3])

In [63]:
array10.max(axis=1)

array([3, 5, 7, 9])

### Sum

In [64]:
# Calculates the sum of all the values

array11 = np.arange(6,15)
array11.sum()

90

**It also supports sum based on axis**

In [65]:
array12= np.arange(6).reshape(3,2)
array12.sum(axis=1)

array([1, 5, 9])

### Mean , StandarDeviation , Median

In [66]:
# Mean

array13 = np.arange(10)
array13.mean()

4.5

In [67]:
# Median

np.median(array13)

4.5

In [68]:
# Standard Deviation

np.std(array13)

2.8722813232690143

### Exponent

In [69]:
array15 = np.arange(10).reshape(2,5)
np.exp(array15)


array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
        5.45981500e+01],
       [1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
        8.10308393e+03]])

### Reshaping Numpy arrays

#### 1 **Ravel function used to bring any dimention to 1D**

In [70]:
# create an array with more than one dimention

a = np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [71]:
# Use ravel function to bring to 1D

a.ravel()

array([0, 1, 2, 3, 4, 5])

#### 2 **Transpose** It converts columns to rows 

a

In [72]:
a.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

#### 3 **Stacking** It combines two arrays

##### Horizontal stack

In [73]:
a1 = np.arange(6).reshape(2,3)
a1

array([[0, 1, 2],
       [3, 4, 5]])

In [74]:
a2 =  np.arange(6,12).reshape(2,3)
a2

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [75]:
np.hstack((a1,a2))

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

##### Vertical stack

In [76]:
a1

array([[0, 1, 2],
       [3, 4, 5]])

In [77]:
a2

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [78]:
np.vstack((a1,a2))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

### 4 **Splitting** it requires two parameters

In [79]:
arr20 = np.arange(10).reshape(2,5)
arr20

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

#### Vertical split (Splits vertically. For ex if two rows then two splits) 

In [80]:
np.vsplit(arr20,2)

[array([[0, 1, 2, 3, 4]]), array([[5, 6, 7, 8, 9]])]

#### horizontal split (Splits horizontally. For ex if five cols then five splits) 

In [81]:
np.hsplit(arr20,5)

[array([[0],
        [5]]),
 array([[1],
        [6]]),
 array([[2],
        [7]]),
 array([[3],
        [8]]),
 array([[4],
        [9]])]

**It also works for single dimention arrays but only hsplit**

In [82]:
arr21 = np.arange(6)
np.hsplit(arr21,6)

[array([0]), array([1]), array([2]), array([3]), array([4]), array([5])]

### Fancy Indexing 

**It is used retreive the values that are discontinous**

In [83]:
a10 = np.arange(24).reshape(6,4)
a10

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [84]:
# We want the data of first , third and fifth row

a10[[0,2,4]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [16, 17, 18, 19]])

### Array generation using Random function

In [85]:
# Take low and high value as required and set the size (how many values you want)

a11 = np.random.randint(low = 1, high = 100, size = 20).reshape(5,4)
a11

array([[81, 48, 95, 13],
       [56, 83, 39, 72],
       [19, 66, 51, 87],
       [35,  3, 52, 23],
       [22, 82, 56,  8]])

In [86]:
### Conditional Indexing (Filtering)

a11>50   # This will return array with same hape but with boolean values

array([[ True, False,  True, False],
       [ True,  True, False,  True],
       [False,  True,  True,  True],
       [False, False,  True, False],
       [False,  True,  True, False]])

In [87]:
# This will provide us with every element that satisfies the condition

a11[a11>50]

array([81, 95, 56, 83, 72, 66, 51, 87, 52, 82, 56])

In [88]:
a11.size

20

In [89]:
a11[(a11>40) & (a11%2==0)]

array([48, 56, 72, 66, 52, 82, 56])

## Plotting graphs using Numpy

In [90]:
x = np.linspace(-40,40,100)
x.size

100

In [91]:
x

array([-40.        , -39.19191919, -38.38383838, -37.57575758,
       -36.76767677, -35.95959596, -35.15151515, -34.34343434,
       -33.53535354, -32.72727273, -31.91919192, -31.11111111,
       -30.3030303 , -29.49494949, -28.68686869, -27.87878788,
       -27.07070707, -26.26262626, -25.45454545, -24.64646465,
       -23.83838384, -23.03030303, -22.22222222, -21.41414141,
       -20.60606061, -19.7979798 , -18.98989899, -18.18181818,
       -17.37373737, -16.56565657, -15.75757576, -14.94949495,
       -14.14141414, -13.33333333, -12.52525253, -11.71717172,
       -10.90909091, -10.1010101 ,  -9.29292929,  -8.48484848,
        -7.67676768,  -6.86868687,  -6.06060606,  -5.25252525,
        -4.44444444,  -3.63636364,  -2.82828283,  -2.02020202,
        -1.21212121,  -0.4040404 ,   0.4040404 ,   1.21212121,
         2.02020202,   2.82828283,   3.63636364,   4.44444444,
         5.25252525,   6.06060606,   6.86868687,   7.67676768,
         8.48484848,   9.29292929,  10.1010101 ,  10.90

y = np.sin(x)
y

**Now we will import matplotlib library to plot graphs**

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline

###### **The line above is used to pause the output on the screen**

In [ ]:
# Now we will plot the graph

plt.plot(x,y)
plt.pause(0.1)

In [ ]:
# We will plot other graph

y1 = x*x + 2*x + 6

plt.plot(x,y1)
plt.pause(0.1)

## **Broadcasting**

**It is a technique offered by the numpy library which is used to perform mathematical operations on arrays that are not similar in shape**

#### Rules

In [ ]:
# If one of the array has 1 then check for equal value to its correspoding in both arrays. If equal then it will execute

x5 = np.arange(8)
x5.ravel() 
x6 = np.arange(16).reshape(2,8)

x5+x6

In [ ]:
# If one of the array has 1 then check for equal value to its correspoding in both arrays. If not then error

x2 = np.arange(8)
x2.ravel() 
x3 = np.arange(14).reshape(2,7)

x2+x3

In [ ]:
# If one of the array has both 1 as shape then it will execute no matter what

x1 = np.array([1]).reshape(1,1)
x4 = np.arange(16).reshape(2,8)

x1+x4

In [ ]:
# If both of the array has one 1 as shape then it will execute

x7 = np.arange(4).reshape(1,4)
x8 = np.arange(4).reshape(4,1)

x7+x8

# Some Important Functions

### 1. Random Function

In [ ]:
# It generates any floating point number randomly

p = np.random.random()
p

**If you want same random value again and again then use SEED function**

In [ ]:
np.random.seed(10)
p = np.random.random()
p

**If you want values in a given range then use UNIFORM function**

In [ ]:
# This will give random values between 5-10

np.random.uniform(5,10)

In [ ]:
# This will give 10 random values between 5-10
np.random.uniform(5,10,10).reshape(2,5)

**If you want integer values the use RANDINT Function**

In [ ]:
# This will create 10 random integer values between 20-60

np.random.randint(20,60,10).reshape(2,5)

### Argmax & Argmin

**These return the indexes of the max and min value**

In [ ]:
a = np.random.randint(20,100,6)
print(a)
print("The index of maximum value is",np.argmax(a))
print("The index of minimum value is",np.argmin(a))

**Problem 1. Replace all the odd values with -1**

<p>To solve this we first create an integer array with some odd values in it. Then we use the conditional indexing to cahnge odd numbers to -1.</p>

In [ ]:
a = np.arange(3,10)
a

In [ ]:
a[a%2!=0] = -1
a

**The above method change the original array.To avoid this we use the WHERE method**

In [ ]:
b = np.arange(3,17)
b

In [ ]:
# it takes three arguements. The condition , value if condition satisfies and value if not satisfy

np.where(b%2!=0,-1,b)